#!/usr/bin/env bash

FILES="./contracts/*.sol"
for f in $FILES
do
  if [[ $f == *"Vault"* ]]; then
    echo "Omitting $f file..."
  elif [[ $f == *"PairStrategy"* ]]; then
    echo "Omitting $f file..."
  else
    echo "Processing $f file..."
    npx hardhat flatten "$f" > "./flat/$f"
  fi
done

FILES="./contracts/util/*.sol"
mkdir -p ./flat/contracts/util/
for f in $FILES
do
  if [[ $f == *"Vault"* ]]; then
    echo "Omitting $f file..."
  else
    echo "Processing $f file..."
    npx hardhat flatten "$f" > "./flat/$f"
  fi
done

FILES="./contracts/mocks/*.sol"
mkdir -p ./flat/contracts/mocks/
for f in $FILES
do
  echo "Processing $f file..."
  npx hardhat flatten "$f" > "./flat/$f"
done
